name: Testing Actions firewall

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-nested:
    runs-on: ubuntu-24.04-firewall
    steps:
      - run: git clone https://github.com/cli/cli.git && cd cli && make && make test

  baseline:
    runs-on: ubuntu-24.04
    steps:
      - run: git clone https://github.com/cli/cli.git && cd cli && make && make test
